[project]
name = "qbittorrent-tagger"
version = "0.2.0"
description = "Script to tag torrents with custom tags based on their properties."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.11.12",
    "qbittorrent-api>=2025.5.0",
    "click>=8.2.1",
]
